#!/usr/bin/env bash

set -e

# Usage: ./run 2024/day01.py    => run the given script (first 'pytest'-ing it if appropriate)
#        ./run 2024             => will find the most recent "dayXX.py" script in year 2024 and run it
#        ./run                  => will find the most recent year, and the most recent "dayXX.py" script inside it, and run it

command -v uv >/dev/null 2>&1 || { 
    echo >&2 "uv is required but it's not installed. Please install uv (https://docs.astral.sh/uv/getting-started/installation/) and try again."; 
    exit 1;
}

if [[ $# -gt 0 ]]; then
    if [[ "$1" =~ ^[0-9]{4}$ ]]; then
        # only a year was given, find the most recent "dayXX.py" in this folder
        YEAR="$1"
        FILE=$(find $YEAR -name day*.py | sort | tail -1)
    else
        FILE=$1
    fi
else
    # find the most recent year folder
    YEAR=$(find . -mindepth 1 -maxdepth 1 -type d  \( ! -iname ".*" \) | grep -E "[[:digit:]]" | sort | tail -1)
    # find the most recent "dayXX.py" in the YEAR/ folder
    FILE=$(find $YEAR -name day*.py | sort | tail -1)
fi

INOTIFYWAIT_EXISTS=$(command -v inotifywait || true)  # true makes the subshell return without stopping the script, but the variable gets assigned an empty string

if grep -q "def test_" $FILE; then
    if [ -z "$INOTIFYWAIT_EXISTS" ]; then
        echo "** inotifywait not found ; if tests fail the script will relaunch every 5 seconds instead of on file changes."
        echo "   Please install inotify-tools to enable auto-reloading tests on file changes."
        echo "   On Debian/Ubuntu: sudo apt-get install inotify-tools"
        echo "***************************************************************************************************************"
    fi

    echo ">>> Running pytest on $FILE"
    FAILED=1
    while [ $FAILED -ne 0 ]; do
        uv run pytest -q --suppress-no-test-exit-code -s "$FILE" && FAILED=0
        if [ $FAILED -ne 0 ]; then
            if [ -z "$INOTIFYWAIT_EXISTS" ]; then
                sleep 5
            else
                inotifywait -e modify -qq "$FILE"  # block until the file is modified
            fi
        fi
    done

    echo
fi

echo ">>> Running $FILE"
PYTHONPATH=. uv run "$FILE"
